//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_resource
    {
        public int user_id { get; set; }
        public int resource_id { get; set; }
        public int amount { get; set; }
    
        public virtual resource resource { get; set; }
        public virtual user user { get; set; }
    }
}
